### ISSUE TITLE
hoppla does not find bridge, when bridge is in different subnet

### ISSUE THREAD

**Issue by Ch3wi3** [Fuchs/hoppla-sa#1]
Steps to reproduce: 

- Bridge with fix IP in subnet 192.168.4.XXX
- Laptop with Kubuntu 16.10 in subnet 192.168.7.XXX
- Subnet 192.168.7.XXX can reach any IP in 192.168.4.XXX via http and ICMP --> other Apps like Hue Pro (Android & iOS) and the offical Philips Apps can reach the bridge from subnet 192.168.7.XXX when given exact IP

**Comment by Fuchs** [comment]
Hi, as QML (the technology to write plasmoids in) does not allow direct UDP request, I have to rely on  https://www.meethue.com/api/nupnp  and can't do an SSDP discovery like android or other apps can  (See also the TODO file).   I assume that the broker simply fails if the bridge is not in the same subnet, you can check that by openign the above URL in a regular web browser. 

If that doesn't work: I'm sorry, I can't fix that in the pure QML variant of the plasmoid, as I have to implement logic. Then, on the other hand, I can't distribute the plasmoid via KDE store (get new plasmoids), as they don't allow distributing logic along *sigh*

Please test the URL, if it works in the browser: I'll try to fix it. If it doesn't work, I'm afraid I have to close it with WONTFIX as I simply can't, due to technology limitations.

**Comment by Ch3wi3** [comment]
I think I found the problem: I simply forgot to put "http://" in front of the bridge IP address. If I do so, the bridge is found and I can authenticate with a button press. I suggest you put some tool-tip or any kind of hint-text on the config page of the plasmoid so it is clear that you have to put "http://" in front. 
Thanks for your support!

**Comment by Fuchs** [comment]
Hi,

This will be solved in the next release with two changes: 

1) A default text is placed in the text field, i18n("http://1.2.3.4, best use \"Find bridge\"");

2) For the base URL (not the Alt URL, on purpose) I check if a protocol part is given in the URL. If not, http:// will be prepended by default  (this would break in the rare case of someone using https in the base URL, but then it is a bit their fault for not adding it, and I can't predict what protocol people use. HTTP is a sane guess, as it is the default and can't be changed easily) 

However, this does not explain the button not working yet, so it'd be great if you could test the above URL regardless. If it doesn't work in a browser with that URL: yes, the broker does not support subnets  (given how SSDP works: understandable).
