### ISSUE TITLE
Existing schedules not parsable

### ISSUE THREAD

**Issue by wweisz** [Fuchs/hoppla-sa#12]
I just installed hoppla-sa v 2.8.2 on openSuSE Linux Leap 15.1.
When I go to editing an existing schedule generated with the Hue app on Android, I get the message: "Failed to parse the specified action. Read only mode, original values are preserved" (as root) or its German translation as a normal user, and no "Command" information for that schedule entry are displayed.

**Comment by Fuchs** [comment]
Hi, it's sort of a known issue, basically when the rule sets fields (or values) that hoppla does not support, the rule is displayed read only because saving it would obviously omit or even alter information. 

I am open to pull requests adding support to additional fields / values, however, I think unless it is well tested that these work, it might make sense to display a warning or the likes before the user can edit it. 

Without knowing what rule you tried to edit, I'm afraid I don't know due to what field(s) it failed to parse.

**Comment by Fuchs** [comment]
closed due to inactivity and missing information.
