### ISSUE TITLE
Hoppla-sa is sometimes crashes KDE

### ISSUE THREAD

**Issue by phisk** [Fuchs/hoppla-sa#20]
When i click on some elements of the widget it sometimes crashes KDE:

I reported it to the KDE-Project and was asked to transfer this information to you:

https://bugs.kde.org/show_bug.cgi?id=421238

Nate Graham <nate@kde.org> changed:

 What    |Removed                     |Added
----------------------------------------------------------------------------
Summary|Hoppla-sa hue control       |Hoppla-sa hue control
               |crashes plasmashell         |crashes plasmashell in
               |                            |ListModel::setExistingPrope
               |                            |rty()
           CC|                            |nate@kde.o
      Status|REPORTED                    |RESOLVED
         Resolution|---                         |DOWNSTREAM

--- Comment #1 from Nate Graham <nate@kde.org> ---
Please report this to the developer of that widget. Thanks!

-- 
You are receiving this mail because:
You reported the bug.

**Comment by Fuchs** [comment]
Hi, what version of the hoppla-sa plasmoid are you using? 
There were a couple of race conditions that I fixed in a recent release that could lead to a plasma crash.

**Comment by phisk** [comment]
I cannot tell which version i had installed. 
In the metadata.desktop it says : X-KDE-PluginInfo-Version=2.6.0
And then i upgraded to version 2.8.4 manually and still the metadata.desktop it says i am X-KDE-PluginInfo-Version=2.6.0
I downloaded all 2.8.x versions and checked the metadata.desktop: all are  X-KDE-PluginInfo-Version=2.6.0
So i do not know which version had been installed on my system before upgrading it.

Due to the manual upgrade i lost all of my custom settings. It would be nice if one could save and restore features like savinng all of the settings (including the bridge connection token), all (and only the) the 'actions', some selected actions or a single action.
If possible in QML :)

**Comment by phisk** [comment]
Now i should be using version 2.8.4. And i will report back if this version crashes, too. This can take while, because the "old" version crashed only a few times a month

**Comment by Fuchs** [comment]
The old version still showing was my bad, I think someone already created a PR for it and I merged it, but didn't package it yet. Sorry. I shall see if I find the time to package a new version next week, also has some other fixes (e.g. I forgot to include the translations).

Settings: Updating should not erase  / overwrite them, removing the plasmoid, on the other hand, does. That's due to how plasmoids store their configuration, and I think it would be nicer to have a KDE/Plasma side solution for that, but I agree that a settings export (and import) would be nice indeed. Thanks for the suggestion, and I hope this resolved the crashes for you :) 

Enjoy the plasmoid

**Comment by phisk** [comment]
Thank you for your reply. I gonna close the issue for now, as it is unknown if the plasmoid is crashing or not (in my use case)
