### ISSUE TITLE
Can't find hue bridge on Fedora 36

### ISSUE THREAD

**Issue by shayanz23** [Fuchs/hoppla-sa#24]
Hello,

I have installed this extension on many distros and it has always worked flawlessly, but for some reason it can't find my Philips hue bridge on fedora 36, is there maybe a setting I should change? I tried disabling my firewall, using "systemctl stop firewalld," and entering my Philips hue bridge's IP manually, but it still wouldn't work.

Thanks for this great widget.

**Comment by Fuchs** [comment]
Hi, 

I am at a F36 box currently and the communication with the bridge does work. The "find bridge" button might indeed rely on firewall rules, plus it calls an external service (https://discovery.meethue.com/), you can check if it works in a browser. 

Adding the IP manually should always work, please note that you do have to prepend the protocol, usually http. 

Example:  http://192.168.0.42   and not only    192.168.0.42

**Comment by shayanz23** [comment]
I just tried the URL you sent me and yeah, it does detect my hue bridge, also I checked the IP I put in manually and it did have the http:// 
This what I have, https://imgur.com/a/YUBPilZ
Is there like an log I can check somewhere?

**Comment by Fuchs** [comment]
Hm, maybe Philips changed something in the way how authentication works. 
However, I just re-authenticated with mine from a Fedora 36 box and it worked as expected. 

If you set this debug mode flag to true: 
https://github.com/Fuchs/hoppla-sa/blob/master/package/contents/code/hue.js#L23
(you can edit that file with a text editor, depending on how you installed the plasmoid it is probably in either /usr/share/plasma/plasmoids/ch.fuchsnet.plasma.hoppla-sa/contents/code/hue.js  or  ~/.local/share/plasma/plasmoids/ch.fuchsnet.plasma.hoppla-sa/contents/code/hue.js)

and restart plasma on a terminal (kquitapp5 plasmashell; plasmashell) it should output lots of debug information into that terminal, and you might be able to find out where it breaks. 

The desktop firewall should not cause this, since all the plasmoid does is creating outgoing http requests and interpreting the answer it gets, so there is no ingoing connection that a firewall would block, and I assume you don't block outgoing http, since that would potentially break other things.

**Comment by shayanz23** [comment]
The only thing I get is 
"file:///home/sz/.local/share/plasma/plasmoids/ch.fuchsnet.plasma.hoppla-sa/contents/code/hue.js:0: ReferenceError: plasmoid is not defined
<Unknown File>: val is null. Adding an object with a null member does not create a role for it.
<Unknown File>: val2 is null. Adding an object with a null member does not create a role for it.
"
and "val2 is not defined"

**Comment by Fuchs** [comment]
Okay, that's odd, and I have no idea how you managed to get that, that should come from import org.kde.plasma.plasmoid 2.0    I think. 

What version of plasma are you using?  
`plasmashell --version `  should give that, but I'd also be interested in the version of KDE frameworks and Qt, you should get that in  `kinfocenter` 

Also is that an up to date version of the plasmoid?

**Comment by shayanz23** [comment]
Im running 
* Plasma 5.24.5
* KDE frameworks 5.93.0 and
* Qt Version 5.15.3

**Comment by Fuchs** [comment]
Okay, almost the same here, except that I have kf 5.94.0, but I doubt that this makes a difference.
That error message is very odd, as I doubt that there are missing packages or imports, as otherwise other plasmoid would not function either. However, this might need some debugging from a  plasma end, so I'd suggest the plasma channel on either Libera.Chat IRC or Matrix (they are bridged, so use whichever you prefer) which might lead to a clue on why it can't find the plasmoid reference, as that is indeed needed for any functionality. 

Unfortunately without being able to reproduce the problem and with having an environment which is almost exactly yours, but working, I can't provide any more pointers. What could be worth a try is seeing if other third party plasmoids installed similarly have the same issue, and if re-installing the plasmoid  (and maybe nuking it's config first, which should be within ~/.config/plasma-org.kde.plasma.desktop-appletsrc) does make any difference, but given the strange error, I'd be surprised if that helped.

**Comment by shayanz23** [comment]
Well actually, Wunderground gave the same error and it is acting strange on my fedora 36 installation too. Detailed info doesn't show up, https://imgur.com/a/B8zHmXr

**Comment by shayanz23** [comment]
That worked, I guess the installation was just borked for some reason then, Thanks!!!

**Comment by Fuchs** [comment]
That's very odd, but I'm glad you got it to work, enjoy 😀
