### ISSUE TITLE
Bluetooth support?

### ISSUE THREAD

**Issue by Mattlau04** [Fuchs/hoppla-sa#25]
Hello, this plasmoid seems really good, but i don't have a hue bridge
However, my PC has a bluetooth card
I therefore wanted to know if there was any way to use this plasmoid with bluetooth instead of a bridge, or if it was a planned feature

**Comment by Fuchs** [comment]
Hi, 

Long answer:
The plasmoid depends heavily on the API that the bridge provides.
Philips / Hue do not make the bluetooth API available to third party developers, so even if I wanted to support bluetooth, I couldn't. Hopefully they revise that decision, but right now if you want to use bluetooth, you are bound to either their app or unofficial products that might break any time.

If somebody reverse engineers it and publishes an unofficial way of talking to it that unfortunately still wouldn't work, as my plasmoid is qml only so it can be distributed without users having to compile / having to rely on distribution packaging, and this couldn't talk to that library either.

Short answer: 
I can't, mostly due to Philips / Hue and technical reasons. Sorry.

**Comment by Mattlau04** [comment]
I see, thanks for the reply!
