### ISSUE TITLE
UI "issue": not enough space or to much content

### ISSUE THREAD

**Issue by Swissbite** [Fuchs/hoppla-sa#26]
Hi @Fuchs,

This issue is an UI issue, not a functional one. Everything seems to work fine, but it is just "not nice" on my system.

The following graphics should explain what is a bit out of the corresponding boxes / grids / lists ....  :-) 

System I am using:
- Tuxedo OS 2 (Ubuntu 22.04 based (LTS))
- KDE Plasma 5.27.5
- KDE Framework 5.106.0
- QT 5.15.9
- Graphic Platform: X11
- Kernel: 6.2.0

![grafik](https://github.com/Fuchs/hoppla-sa/assets/205621/1d81e2d4-b4bf-484f-9b9f-8831c4ecfbe6)
![grafik](https://github.com/Fuchs/hoppla-sa/assets/205621/87f5fb30-5552-4e60-a593-69f65a077bf8)

**Comment by Fuchs** [comment]
Hi, thanks for the report and apologies for the inconvenience. It should not do that, I thought I fixed most of these, most recently with 

https://github.com/Fuchs/hoppla-sa/commit/d6c3ae498bff825cbb2ac9510d10ff6959bd62df

I'm not sure if I ever packed that in a release, you can check GroupItem.qml (it's a text file) with your text editor and, if that fix is not already in there, add it. Depending on how you installed the plasmoid it might either be in /usr/share/plasma/plasmoids or ~/.local/share/plasma/plasmoids/ under  ch.fuchsnet.plasma.hoppla-sa/contents/ui/

Otherwise I'll try to look into it, unfortunately I am currently rather busy and rarely have time to maintain stuff.

**Comment by Fuchs** [comment]
Nevermind, just saw the checkbox on your screenshot, so you definitely have a bit of an outdated version. See if you can install the most recent one  (instructions to get it right from GitHub should be in the instructions, note that depending on how you installed your current version you have to remove that) and it's most likely fixed in that :)

**Comment by Swissbite** [comment]
Thank you for your replay.

I installed it over the KDE store, therfore version 4.0.0 . I'll try to install it by checkout and compile by myself.

**Comment by Swissbite** [comment]
**Update**
I cloned the repo, changed the version to 4.0.1 (just to test if it is using the correct application and get rid of caching issues), and installed it by `plasmapkg2 -i package`

Then it worked. So technically, the bug has been resolved. It would be nice to have it on the KDE store for non-tech guys 😉

**Comment by Fuchs** [comment]
Glad to hear it is resolved, I'll see if I can bundle up a fix release, it's unfortunately a lot more complicated and time consuming than one might think.
