### ISSUE TITLE
Too easy to delete a group

### ISSUE THREAD

**Issue by derEremit** [Fuchs/hoppla-sa#8]
Hi I was just testing your awesome app.
It works really fine, but just on the first try I immediately deleted 2 Groups by accident.

At first:
For a first time user you are not immediately aware you're actually deleting the group from hue and not only from the plasmoid ( was my first thought)
secondly:
a tooltip when you delete anything is always very much appreciated in ANY application :+1: 
And it is really hurting if you delete hue groups which had scenes and everything connected.

**Comment by Fuchs** [comment]
Hi, 

thank you for your feeback. There is a tooltip for every button in that list, including remove. 
I assume that is how you deleted them?  (Because I am not aware of any other way)

What I can do (if I find out how) is to add a confirmation dialogue for destructive actions. I thought I had that, but I can't test right now, so chances are that indeed I don't.

My plasmoid is almost entirely stateless  (except the own actions you can add), so I take groups and lights from Hue and therefore you can't delete them from the plasmoid only.

I'll see when I find some time to dig into confirmation dialogues and add them to potentially destructive actions, that makes sense.

**Comment by Fuchs** [comment]
Please update to 2.8.0 which has just been released and contains confirmation dialogues for deleting groups, lights, schedules and actions.
